name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
    
      - name: Build
        run: |
          npm run build
          echo "javascript:((() => { $(cat dist/femto_edit.js)})())" > dist/femto_edit_bookmarklet.js
    
      - name: Create bookmarklet markdown
        id: bookmarklet
        run: |
          echo "bookmarklet<<EOF" >> $GITHUB_OUTPUT
          cat dist/femto_edit_bookmarklet.js | sed 's/\\/\\\\/g; s/"/\\"/g; s/'"'"'/\\'"'"'/g' >> $GITHUB_OUTPUT
          echo EOF >> $GITHUB_OUTPUT
    
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/femto_edit.js, dist/femto_edit_bookmarklet.js
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: |
            Automated release from commit ${{ github.sha }}
            
            Changes in this release:
            ${{ github.event.head_commit.message }}
    
            ## Bookmarklet
            <a href='${{ steps.bookmarklet.outputs.bookmarklet }}'>Bookmarklet</a>
    
            You can also find the raw bookmarklet in the releases assets.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}